create database rwby;

CREATE  TABLE IF NOT EXISTS rwby.`ACCOUNT` (
	`ID_ACCOUNT` INT NOT NULL ,
	`NUMBER` VARCHAR(45) NULL ,
	`BILL` DOUBLE NULL ,
	`DELETED` TINYINT(1) NULL ,
	PRIMARY KEY (`ID_ACCOUNT`) );


CREATE  TABLE IF NOT EXISTS rwby.`USER_T` (
	`ID_USER` INT NOT NULL ,
	`LOGIN` VARCHAR(45) NULL ,
	`PASSWORD` VARCHAR(45) NULL ,
	`FIRST_NAME` VARCHAR(45) NULL ,
	`LAST_NAME` VARCHAR(45) NULL ,
	`EMAIL` VARCHAR(45) NULL ,
	`DELETED` TINYINT(1) NULL DEFAULT false ,
	`ROLE` INT NOT NULL ,
	`ACCOUNT_ID` INT NULL ,
	PRIMARY KEY (`ID_USER`)
	);

    
ALTER TABLE rwby.`USER_T` ADD CONSTRAINT `fk_USER_ACCOUNT1`
	FOREIGN KEY (`ACCOUNT_ID` )
	REFERENCES rwby.`ACCOUNT` (`ID_ACCOUNT` );
	
	
CREATE  TABLE IF NOT EXISTS rwby.`STATION` (
	`ID_STATION` INT NOT NULL ,
	`NAME_STATION` VARCHAR(45) NULL ,
	PRIMARY KEY (`ID_STATION`) );


CREATE  TABLE IF NOT EXISTS rwby.`MAP_STATION` (
	`ID_MAP_STATION` INT NOT NULL ,
	`STATION_DEPARTURE` INT NOT NULL ,
	`STATION_ARRIVAL` INT NOT NULL ,
	`TIME` TIME NULL ,
	`DISTANCE` INT NULL ,
	PRIMARY KEY (`ID_MAP_STATION`));

ALTER TABLE rwby.MAP_STATION ADD CONSTRAINT `fk_MAP_STATION_STATION1`
	FOREIGN KEY (`STATION_DEPARTURE`)
	REFERENCES rwby.`STATION` (`ID_STATION`);

ALTER TABLE rwby.MAP_STATION ADD CONSTRAINT `fk_MAP_STATION_STATION2`
	FOREIGN KEY (`STATION_ARRIVAL`)
	REFERENCES rwby.`STATION` (`ID_STATION`);
	
	
CREATE  TABLE IF NOT EXISTS rwby.`TRAIN` (
	`ID_TRAIN` INT NOT NULL ,
	`NUMBER` INT NULL ,
	`TIME_DEPARTURE` TIME NULL ,
	PRIMARY KEY (`ID_TRAIN`) );

  
CREATE  TABLE IF NOT EXISTS rwby.`TRAIN_MAP_STATION` (
	`ID_TRAIN_MAP_STATION` INT NOT NULL ,
	`MAP_STATION_ID` INT NOT NULL ,
	`TRAIN_ID` INT NOT NULL ,
	`SEQ_NO` INT NULL ,
	PRIMARY KEY (`ID_TRAIN_MAP_STATION`)
	);
	
ALTER TABLE rwby.`TRAIN_MAP_STATION` ADD CONSTRAINT `fk_TRAIN_MAP_STATION_MAP_STATION1`
	FOREIGN KEY (`MAP_STATION_ID` )
	REFERENCES rwby.`MAP_STATION` (`ID_MAP_STATION` );

ALTER TABLE rwby.`TRAIN_MAP_STATION` ADD CONSTRAINT `fk_TRAIN_MAP_STATION_TRAIN1`
	FOREIGN KEY (`TRAIN_ID` )
	REFERENCES rwby.`TRAIN` (`ID_TRAIN` );

CREATE  TABLE IF NOT EXISTS rwby.`TYPE_WAGON` (
	`ID_TYPE_WAGON` INT NOT NULL ,
	`TYPE` VARCHAR(45) NULL ,
	`NUMBER_SEATS` INT NULL ,
	`COEFFICIENT` INT NULL ,
	PRIMARY KEY (`ID_TYPE_WAGON`) 
	);
  
CREATE  TABLE IF NOT EXISTS rwby.`WAGON` (
	`ID_WAGON` INT NOT NULL ,
	`TYPE_WAGON` INT NOT NULL ,
	`NUMBER` INT NULL ,
	`TRAIN_ID` INT NOT NULL ,
	PRIMARY KEY (`ID_WAGON`)
	);

ALTER TABLE rwby.`WAGON` ADD CONSTRAINT `fk_WAGON_TYPE_WAGON1`
    FOREIGN KEY (`TYPE_WAGON` )
    REFERENCES rwby.`TYPE_WAGON` (`ID_TYPE_WAGON` );
	
ALTER TABLE rwby.`WAGON` ADD CONSTRAINT `fk_WAGON_TRAIN1`
    FOREIGN KEY (`TRAIN_ID` )
    REFERENCES rwby.`TRAIN` (`ID_TRAIN` );
	

 CREATE  TABLE IF NOT EXISTS rwby.`TICKET` (
	`ID_TICKET` INT NOT NULL ,
	`NUMBER_TICKET` INT NULL ,
	`TIME_DEPARTURE` VARCHAR(45) NULL ,
	`TIME_ARRIVAL` VARCHAR(45) NULL ,
	`TIME_ARRIVAL` VARCHAR(45)  ,
	`TRAIN_NAME` VARCHAR(45)  ,
	`PRICE` VARCHAR(45)  ,
	`STATION_DEPARTURE` VARCHAR(45) NULL ,
	`STATION_ARRIVAL` VARCHAR(45) NULL ,
	`USER_ID` INT NOT NULL ,
	`WAGON_ID` INT NOT NULL ,
	PRIMARY KEY (`ID_TICKET`)
	);
	
	
ALTER TABLE rwby.`TICKET` ADD CONSTRAINT `fk_TICKET_USER_1`
	FOREIGN KEY (`USER_ID` )
	REFERENCES rwby.`USER_T` (`ID_USER` );
	
ALTER TABLE rwby.`TICKET` ADD CONSTRAINT `fk_TICKET_WAGON1`
	FOREIGN KEY (`WAGON_ID` )
	REFERENCES rwby.`PLACE` (`ID_WAGON` );
	
	
CREATE  TABLE `rwby`.`MESSAGE` (
  `ID_MESSAGE` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  `MESSAGE` TEXT NULL ,
  `TYPE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID_MESSAGE`) );
  
  
CREATE  TABLE IF NOT EXISTS rwby.`TRAIN_DATE` (
 `ID_TRAIN_DATE` INT NOT NULL ,
 `DEPARTURE_DATE` DATE NOT NULL ,
 `DEPARTURE_TIME` TIME NOT NULL ,
 `TRAIN_ID` INT NOT NULL ,
 PRIMARY KEY (`ID_TRAIN_DATE`)
 );
  
ALTER TABLE rwby.`TRAIN_DATE` ADD CONSTRAINT `fk_TRAIN_12`
	FOREIGN KEY (`TRAIN_ID` )
	REFERENCES rwby.`TRAIN` (`ID_TRAIN` );
 
CREATE  TABLE IF NOT EXISTS rwby.`RESERVED_TICKET` (
 `ID_RESERVED_TICKET` INT NOT NULL ,
 `TRAIN_DATE_ID` INT NOT NULL ,
 `TICKET_ID` INT NOT NULL ,
 PRIMARY KEY (`ID_RESERVED_TICKET`)
 );

ALTER TABLE rwby.`RESERVED_TICKET` ADD CONSTRAINT `fk_TRAIN_DATE_ID_13`
	FOREIGN KEY (`TRAIN_DATE_ID` )
	REFERENCES rwby.`TRAIN_DATE` (`ID_TRAIN_DATE` );

ALTER TABLE rwby.`RESERVED_TICKET` ADD CONSTRAINT `fk_TICKET_ID_14`
	FOREIGN KEY (`TICKET_ID` )
	REFERENCES rwby.`TICKET` (`ID_TICKET` );
	
	
CREATE  TABLE `rwby`.`MESSAGE` (
  `ID_MESSAGE` INT NOT NULL ,
  `NAME` VARCHAR(45) NULL ,
  `EMAIL` VARCHAR(45) NULL ,
  `MESSAGE` TEXT NULL ,
  `TYPE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID_MESSAGE`) );

