--﻿CREATE TABLE news
--(
--   id_news   NUMBER,
--   title     VARCHAR2 (100 BYTE),
--   "DATE"    DATE DEFAULT SYSDATE,
--   brief     VARCHAR2 (500 BYTE),
--   content   LONG
--)
--NOCACHE
--LOGGING;